M48
; DRILL file {KiCad 9.0.3} date 2025-07-23T10:37:10+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-07-23T10:37:10+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1213
%
G90
G05
T1
X5.6358Y-3.6614
X5.8209Y-3.6614
T2
X4.4409Y-3.6611
X5.0984Y-3.6611
M30
