M48
; DRILL file {KiCad 9.0.6-9.0.6~ubuntu25.04.1} date 2025-12-27T15:19:46+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-27T15:19:46+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6-9.0.6~ubuntu25.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.080
%
G90
G05
T1
X143.15Y-93.0
X147.85Y-93.0
T2
X112.8Y-92.992
X129.5Y-92.992
M30
